### ISSUE TITLE
Messages are rejected. 

### ISSUE THREAD

**Issue by EmaEvidence** [azemoh/jusibe#4]
I have 998 SMS credit but all messages sent either from my web app or directly from the jusibe website is rejected.

**Comment by azemoh** [comment]
Hi, @EmaEvidence. Sorry for the delayed response. This is a third-party library and I have no affiliation with the Jusibe team. You can reach out to them if you have issues with your account. [[contact]](https://jusibe.com/support/)

Closing this issue now.
